---
- hosts: server2.abc.com
  user: root
  sudo: yes
  gather_facts: yes
  tasks:
    - name: remove older version
      file: path=/usr/local/tomcat state=absent
    - name: download apache
      get_url: http://redrockdigimark.com/apachemirror/tomcat/tomcat-7/v7.0.73/bin/apache-tomcat-7.0.73.tar.gz dest=/tmp
    - name: extract archive
      unarchive: src=/tmp/apache-tomcat-7.0.73.tar.gz dest=/tmp copy=no
    - name: make the directory
      command: mkdir /usr/local/tomcat
    - name: move the directory
      command: mv /tmp/apache-tomcat-7.0.73 /usr/local/tomcat
    - name: start tomcat
      command: nohup /usr/local/tomcat/apache-tomcat-7.0.73/bin/./startup.sh  
      

