---
- hosts: '{{ hosts }}'
#- hosts: server2.abc.com
  user: root
  sudo: yes
  gather_facts: yes
  vars:
     pkg: httpd
 # vars_files:
 #   - playbook/abc.yml
 # vars_prompt:
 #  - name: pkg2
 #    prompt: enter the package name
 #    private: no
  tasks:
   - name: install httpd package
     yum: name={{pkg}} state=installed
 # - name: install curl server
 #     yum: name={{pkg1}} state=installed
   - name: pause
     pause:
        prompt: press enter to 
 # - name: install telnet
 #    yum: name={{pkg2}} state=installed
   - name: copy index file
     copy: src=/etc/ansible/playbook/index.html dest=/var/www/html
   - name: start the service 
     service: name=httpd state=started
     register: result
   - debug: var=result
  
